### ISSUE TITLE
win

### ISSUE THREAD

**Issue by Root-warning** [secistgroup/SecistSploit#10]
Traceback (most recent call last):
  File "ssfconsole.py", line 5, in <module>
    from core.Main import Interpreter
  File "C:\Users\Psycho\Desktop\SecistSploit-develop\core\Main.py", line 18, in <module>
    from core.Prompt import *
  File "C:\Users\Psycho\Desktop\SecistSploit-develop\core\Prompt.py", line 15, in <module>
    open(history_path, 'w+').close()
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ssfhistory'

**Comment by c4dr01d** [comment]
代码已经修复关于win下的问题
